site_name: scTAPE
repo_url: https://github.com/poseidonchan/TAPE
site_author: 'Yanshuo CHEN'
docs_dir: 'docs'
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Datasets: datasets.md
  - Experiments: experiments.md
theme: readthedocs